name: myweb
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0-406.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test: 
    sdk: flutter
  pedantic: ^1.9.2

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: RB
      fonts:
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-Regular.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Mono/static/RobotoMono-SemiBold.ttf
          weight: 600
    - family: IBM
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans_KR/IBMPlexSansKR-Regular.ttf
          weight: 300
        - asset: assets/fonts/IBM_Plex_Sans_KR/IBMPlexSansKR-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBM_Plex_Sans_KR/IBMPlexSansKR-Bold.ttf
          weight: 800

